2024-03-08 11:09:12,214: [11] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2024-03-08 11:09:12,215: [11] m.main:INFO: Beginning analysis
2024-03-08 11:09:12,217: [11] m.e.manticore:INFO: Starting symbolic create contract
2024-03-08 11:09:12,653: [11] m.e.manticore:INFO: Starting symbolic transaction: 0
2024-03-08 11:09:17,838: [11] m.e.manticore:INFO: 7 alive states, 2 terminated states
2024-03-08 11:09:18,064: [79] m.c.manticore:INFO: Generated testcase No. 0 - STOP(2 txs)
2024-03-08 11:09:18,066: [79] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2024-03-08 11:09:18,071: [83] m.c.manticore:INFO: Generated testcase No. 1 - STOP(2 txs)
2024-03-08 11:09:18,072: [83] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2024-03-08 11:09:18,073: [80] m.c.manticore:INFO: Generated testcase No. 3 - STOP(2 txs)
2024-03-08 11:09:18,074: [85] m.c.manticore:INFO: Generated testcase No. 2 - STOP(2 txs)
2024-03-08 11:09:18,075: [80] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2024-03-08 11:09:18,075: [85] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2024-03-08 11:09:18,089: [87] m.c.manticore:INFO: Generated testcase No. 4 - STOP(2 txs)
2024-03-08 11:09:18,090: [87] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2024-03-08 11:09:18,104: [90] m.c.manticore:INFO: Generated testcase No. 5 - STOP(2 txs)
2024-03-08 11:09:18,106: [90] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
Traceback (most recent call last):
  File "/usr/local/bin/manticore", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/manticore/__main__.py", line 42, in main
    ethereum_main(args, logger)
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/cli.py", line 145, in ethereum_main
    m.finalize(only_alive_states=args.only_alive_testcases)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 177, in newFunction
    return func(self, *args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/manticore.py", line 1811, in finalize
    "{:x}: {:2.2f}%\n".format(int(address), self.global_coverage(address))
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/manticore.py", line 1888, in global_coverage
    runtime_bytecode = state.solve_one(code)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/state.py", line 483, in solve_one
    return self.solve_one_n(expr, constrain=constrain)[0]
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/state.py", line 494, in solve_one_n
    return self.solve_one_n_batched(exprs, constrain)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/state.py", line 509, in solve_one_n_batched
    values = self._solver.get_value_in_batch(self._constraints, exprs)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/smtlib/solver.py", line 745, in get_value_in_batch
    "Solver could not find a value for expression under current constraint set"
manticore.exceptions.SolverError: Solver could not find a value for expression under current constraint set
